### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by tipsy** [javalin/javalin-graphql#1]
We're moving `javalin-graphql` out of the main Javalin repo (`javalin/javalin`) and into `javalin/javalin-graphql`. We are looking for a maintaner for this repo. 

Are you interested in doing this. @7agustibm ? You've done a great job of maintaining it so far :)

**Comment by 7agustibm** [comment]
Hi @tipsy! When I have a moment, I'll do it.

**Comment by tipsy** [comment]
Great @7agustibm, I will promote you to admin :)
