### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tipsy** [javalin/javalin-graphql#3]
Hi @7agustibm - Javalin 5 is getting close, so it would be good if we could get this released. Are you able to manage this yourself?

**Comment by 7agustibm** [comment]
I believe so. I take a look at it.

**Comment by tipsy** [comment]
Great, thank you!

**Comment by 7agustibm** [comment]
Hi @tipsy! 

Do you know what this error could be?

```
Execution failed for task ':publishLibraryPublicationToReposilite-repositoryRepository'.
[67](https://github.com/javalin/javalin-graphql/actions/runs/3213927255/jobs/5253979138#step:4:69)
> Failed to publish publication 'library' to repository 'reposilite-repository'
[68](https://github.com/javalin/javalin-graphql/actions/runs/3213927255/jobs/5253979138#step:4:70)
   > Could not PUT 'https://maven.reposilite.com/snapshots/io/javalin/community/graphql/javalin-graphql/5.0.1-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
[69](https://github.com/javalin/javalin-graphql/actions/runs/3213927255/jobs/5253979138#step:4:71)
```

Maybe this repository need acces to org secrets?

**Comment by tipsy** [comment]
> Maybe this repository need acces to org secrets?

We don't have any secrets or shared setup for deploying. If you want to deploy under `io.javalin.community.graphql` we need to contact the sonatype people to create credentials for your user.

**Comment by dzikoysk** [comment]
In general it could be a good idea to push stable release to Maven Central, take a look at:

* https://github.com/javalin/javalin/issues/1660

Anyway, I can also generate you token for `maven.reposilite.com`, so you can push snapshot builds, that's what we do in javalin-openapi & javalin-ssl plugins.

**Comment by 7agustibm** [comment]
Hi @dzikoysk! I believe it's the best way us create this token for maven.reposilite.com. Can you create it?

**Comment by 7agustibm** [comment]
Hi! I'm starting process in Maven Central. I'm following this process: https://central.sonatype.org/publish/publish-guide/#introduction

**Comment by tipsy** [comment]
@7agustibm if you sign up at https://issues.sonatype.org and tell me your username, I can ask them to create `io.javalin.community.graphql` and give your user publishing rights.

**Comment by dzikoysk** [comment]
If you want token for snapshots just DM me somewhere, so I can give you credentials :) 

<details>
  <summary>Contact</summary>

```
Mail: dzikoysk[at]dzikoysk.net
Discord: dzikoysk#0001
Twitter: @dzikoysk
```

</details>

**Comment by 7agustibm** [comment]
Hi @tipsy! My user is agustibm.

**Comment by tipsy** [comment]
I've requested they add your user: https://issues.sonatype.org/browse/OSSRH-84953

**Comment by zugazagoitia** [comment]
Hey @7agustibm, if you've got any issues with setting this up I'll be happy to help, even in spanish if you'd like.

**Comment by 7agustibm** [comment]
Thanks guys! This weekend I will upload the artifact.

**Comment by tipsy** [comment]
🎉 

The readme still has reposilite in the install instructions, but I guess this is not required if you published to Maven Central now.
